<a href="https://colab.research.google.com/github/nhosamani/Numpy/blob/main/assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
#1. Create a null vector of size 10 but the fifth value which is 1.
import numpy as np
a=np.zeros(10);
a[4]=1;
a

# OR 
b=np.arange(10)==4;
b=b*1;
b

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [17]:
#2. Create a vector with values ranging from 10 to 49.
a=np.arange(10,50)
a




array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [28]:
#3.Create a 3x3 matrix with values ranging from 0 to 8
m=np.arange(0,9).reshape(3,3)
m




array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]
a=np.array([1,2,0,0,4,0]);
np.nonzero(a);
np.transpose(np.nonzero(a))

array([[0],
       [1],
       [4]])

In [58]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.
np.random.seed(0);
a=np.random.rand(10,10);
print("array",a)
max=np.max(a)
min=np.min(a)
print("Max is",max)
print("Min is",min)

array [[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
  0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606 0.0871293
  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443 0.63992102
  0.14335329 0.94466892 0.52184832 0.41466194]
 [0.26455561 0.77423369 0.45615033 0.56843395 0.0187898  0.6176355
  0.61209572 0.616934   0.94374808 0.6818203 ]
 [0.3595079  0.43703195 0.6976312  0.06022547 0.66676672 0.67063787
  0.21038256 0.1289263  0.31542835 0.36371077]
 [0.57019677 0.43860151 0.98837384 0.10204481 0.20887676 0.16130952
  0.65310833 0.2532916  0.46631077 0.24442559]
 [0.15896958 0.11037514 0.65632959 0.13818295 0.19658236 0.36872517
  0.82099323 0.09710128 0.83794491 0.09609841]
 [0.97645947 0.4686512  0.97676109 0.60484552 0.73926358 0.03918779
  0.28280696 0.12019656 0.2961402  0.11872772]
 [0.31798318 0.41426299 0.0641475  0.69247212 0.56660145 0.26538949
  0.5232

In [61]:
#6. Create a random vector of size 30 and find the mean value.
np.random.seed(10)
a=np.random.rand(30)
print("array",a)
mean=np.mean(a)
print("mean",mean)


array [0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]
mean 0.5110090641579068
